# TCL File Generated by Component Editor 18.1
# Tue Jun 13 17:56:16 BST 2023
# DO NOT MODIFY


# 
# spi_test "spi_test" v1.0
#  2023.06.13.17:56:16
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module spi_test
# 
set_module_property DESCRIPTION ""
set_module_property NAME spi_test
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME spi_test
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL spi_stream_test
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file spi_stream_test.sv SYSTEM_VERILOG PATH spi_stream_test.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter IMAGE_W STD_LOGIC_VECTOR 320
set_parameter_property IMAGE_W DEFAULT_VALUE 320
set_parameter_property IMAGE_W DISPLAY_NAME IMAGE_W
set_parameter_property IMAGE_W WIDTH 13
set_parameter_property IMAGE_W TYPE STD_LOGIC_VECTOR
set_parameter_property IMAGE_W UNITS None
set_parameter_property IMAGE_W ALLOWED_RANGES 0:8191
set_parameter_property IMAGE_W HDL_PARAMETER true
add_parameter IMAGE_H STD_LOGIC_VECTOR 240
set_parameter_property IMAGE_H DEFAULT_VALUE 240
set_parameter_property IMAGE_H DISPLAY_NAME IMAGE_H
set_parameter_property IMAGE_H WIDTH 13
set_parameter_property IMAGE_H TYPE STD_LOGIC_VECTOR
set_parameter_property IMAGE_H UNITS None
set_parameter_property IMAGE_H ALLOWED_RANGES 0:8191
set_parameter_property IMAGE_H HDL_PARAMETER true
add_parameter MESSAGE_BUF_MAX INTEGER 256
set_parameter_property MESSAGE_BUF_MAX DEFAULT_VALUE 256
set_parameter_property MESSAGE_BUF_MAX DISPLAY_NAME MESSAGE_BUF_MAX
set_parameter_property MESSAGE_BUF_MAX TYPE INTEGER
set_parameter_property MESSAGE_BUF_MAX UNITS None
set_parameter_property MESSAGE_BUF_MAX ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MESSAGE_BUF_MAX HDL_PARAMETER true
add_parameter MSG_INTERVAL INTEGER 6
set_parameter_property MSG_INTERVAL DEFAULT_VALUE 6
set_parameter_property MSG_INTERVAL DISPLAY_NAME MSG_INTERVAL
set_parameter_property MSG_INTERVAL TYPE INTEGER
set_parameter_property MSG_INTERVAL UNITS None
set_parameter_property MSG_INTERVAL ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MSG_INTERVAL HDL_PARAMETER true
add_parameter BB_COL_DEFAULT STD_LOGIC_VECTOR 65280
set_parameter_property BB_COL_DEFAULT DEFAULT_VALUE 65280
set_parameter_property BB_COL_DEFAULT DISPLAY_NAME BB_COL_DEFAULT
set_parameter_property BB_COL_DEFAULT WIDTH 26
set_parameter_property BB_COL_DEFAULT TYPE STD_LOGIC_VECTOR
set_parameter_property BB_COL_DEFAULT UNITS None
set_parameter_property BB_COL_DEFAULT ALLOWED_RANGES 0:67108863
set_parameter_property BB_COL_DEFAULT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clk
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink sink_data data Input 24
add_interface_port avalon_streaming_sink sink_ready ready Output 1
add_interface_port avalon_streaming_sink sink_valid valid Input 1
add_interface_port avalon_streaming_sink sink_sop startofpacket Input 1
add_interface_port avalon_streaming_sink sink_eop endofpacket Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point spi_clock_source
# 
add_interface spi_clock_source clock end
set_interface_property spi_clock_source clockRate 0
set_interface_property spi_clock_source ENABLED true
set_interface_property spi_clock_source EXPORT_OF ""
set_interface_property spi_clock_source PORT_NAME_MAP ""
set_interface_property spi_clock_source CMSIS_SVD_VARIABLES ""
set_interface_property spi_clock_source SVD_ADDRESS_GROUP ""

add_interface_port spi_clock_source spi_clock_source clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point spi_conduit
# 
add_interface spi_conduit conduit end
set_interface_property spi_conduit associatedClock clk
set_interface_property spi_conduit associatedReset ""
set_interface_property spi_conduit ENABLED true
set_interface_property spi_conduit EXPORT_OF ""
set_interface_property spi_conduit PORT_NAME_MAP ""
set_interface_property spi_conduit CMSIS_SVD_VARIABLES ""
set_interface_property spi_conduit SVD_ADDRESS_GROUP ""

add_interface_port spi_conduit spi_miso new_signal Input 1
add_interface_port spi_conduit spi_mosi new_signal_1 Input 1
add_interface_port spi_conduit spi_ss new_signal_2 Input 1
add_interface_port spi_conduit spi_clk new_signal_3 Input 1

